In [1]:
# Importing the packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import statistics

In [8]:
filtered = pd.read_csv('/Users/Emily/Desktop/filteredS1.csv',  usecols=['Total Worms', 'Chemotaxis', 'Compound'])

In [9]:
filtered[filtered['Compound'].isin([''])]

   Total Worms  Chemotaxis     Compound
0          387    0.095808  (+)-Carvone
1          408   -0.041096  (+)-Carvone
2          257    0.205021  (+)-Carvone
3          325   -0.086667  (-)-Borneol
4          203    0.088889  (-)-Borneol

In [10]:
filtered.groupby(by='Compound').mean()

                      Total Worms  Chemotaxis
Compound
(+)-Carvone            350.666667    0.086578
(-)-Borneol            289.000000   -0.054634
(-)-Cedrene            345.333333    0.128944
(-)-Huperzine A        303.666667    0.248711
1-octanol              217.333333   -0.458012
...                           ...         ...
p-Anisic acid          341.333333   -0.076448
p-Tolualdehyde         291.000000    0.189825
trans-Cinnamaldehyde   293.000000    0.019462
α-Phellandrene         259.000000    0.341553
β-Citronellol          286.666667    0.190089

[96 rows x 2 columns]